input {
  beats {
    port => 5044
  }
}

filter {
  grok {
    match => {
      "message" => "%{SYSLOGTIMESTAMP:timestamp} %{HOSTNAME:host} %{WORD:program}(?:\[%{POSINT:pid}\])?: %{GREEDYDATA:log_message}"
    }
  }

  if "Failed password" in [log_message] {
    mutate { add_tag => ["failed_login"] }
  }

  if "Accepted" in [log_message] {
    mutate { add_tag => ["success_login"] }
  }

  if "sudo" in [program] {
    mutate { add_tag => ["sudo_activity"] }
  }

  date {
    match => ["timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "auth-logs-%{+YYYY.MM.dd}"
  }
}
